AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM template to launch an API that serves data from a connected data source

Globals:
  Function:
    Runtime: python3.8
    Handler: index.handler
    Timeout: 30
    Environment:
      Variables:
        TABLE_NAME: !Ref DynamoDbTable

Resources:
  DynamoDbTable:
    Type: AWS::Serverless::SimpleTable

  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Ref AWS::StackName
      StageName: dev

  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies: AWSLambdaDynamoDBExecutionRole
      Events:
        Api:
          Type: Api
          Properties:
            Method: get
            Path: /helloworld
            RestApiId: !Ref Api
      InlineCode: |
        import json
        import boto3
        import os

        def handler(event, context):
          ddbTableName = os.environ.get('TABLE_NAME')
          print("Table name is " + ddbTableName)
          dynamodb = boto3.resource('dynamodb')
          table = dynamodb.Table(ddbTableName)
          return {
            'statusCode': 200,
            'body': json.dumps('Hello from Lambda!')
          }
